spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/myWeb_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: psw_web
    password: web123123!

  # attachfile
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/psw/github/filess