server:
    port: 8089
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    application:
        name: myWeb
    profiles:
        active: local

# mysql datetime 과 return datetime
    jackson:
        deserialization:
            adjust-dates-to-context-time-zone: false
        time-zone: Asia/Seoul

# mustache
    mustache:
        enabled: true
        charset: UTF-8
        suffix": .html
        check-template-location: true

# mybatis (MyBatisConfig.java same functions)
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.melly.myweb
    configuration:
        map-underscore-to-camel-case: true
